# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VueZ
                                 A QGIS plugin
 plugin generique
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Gérôme PECHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from PyQt5.QtWidgets import QApplication, QMessageBox
from PyQt5.QtCore import Qt
from owslib.owscontext.geojson import decode_json
from qgis.core import QgsProject,QgsVectorLayer, QgsGeometry, QgsPoint, QgsFeature, QgsFeatureRequest, \
     QgsPalLayerSettings, QgsTextFormat, QgsTextBufferSettings, QgsVectorLayerSimpleLabeling, \
    QgsMarkerSymbol, QgsSingleSymbolRenderer,QgsCoordinateTransform


class VueZ:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        # Save reference to the QGIS interface
        self.iface = iface
        self.layer = None
        self.deja_affiche = False


    def creer_vue_altitude(self):
        self.layer = self.iface.activeLayer()
        if self.layer is None:
            QMessageBox.warning(None,"Avertissement","Aucune couche n'est active")
            return

        QApplication.setOverrideCursor(Qt.WaitCursor)

        canvas = self.iface.mapCanvas()

        project = QgsProject.instance()
        project_crs = project.crs()
        layer_crs = self.layer.crs()

        extent = canvas.extent()
        # Reprojection de l'emprise vers le CRS de la couche
        if project_crs != layer_crs:
            transform = QgsCoordinateTransform(project_crs, layer_crs, project)
            extent = transform.transformBoundingBox(extent)

        # Créer la couche mémoire
        # Vérifier si la couche "Altitude" existe déjà
        existing_layers = project.mapLayersByName("Altitude")
        if existing_layers:
            out = existing_layers[0]
            # Supprimer toutes les entitées existantes
            out.dataProvider().truncate()
        else:
            # Créer la couche mémoire
            out = QgsVectorLayer(f"PointZ?crs={layer_crs.authid()}&field=z:double", "Altitude", "memory")
            project.addMapLayer(out)
        pr = out.dataProvider()

        fields = out.fields()
        new_entite = []
        append_entite = new_entite.append  # optimisation

        for feature in self.layer.getFeatures(QgsFeatureRequest().setFilterRect(extent)):
            for sommet in feature.geometry().vertices():
                entite = QgsFeature(fields)
                entite.setGeometry(QgsGeometry.fromPoint(QgsPoint(sommet.x(), sommet.y(), sommet.z())))
                entite["z"] = sommet.z()
                append_entite(entite)

        pr.addFeatures(new_entite)

        symbol = QgsMarkerSymbol.createSimple({'name': 'circle','size': '1' })
        renderer = QgsSingleSymbolRenderer(symbol)
        out.setRenderer(renderer)
        out.triggerRepaint()

        # QgsProject.instance().addMapLayer(out)
        layer_tree = QgsProject.instance().layerTreeRoot().findLayer(out.id())
        layer_tree.setItemVisibilityChecked(True)
        self.set_etiquette_altitude()

        self.iface.setActiveLayer(self.layer)

        QApplication.restoreOverrideCursor()


    def set_etiquette_altitude(self):
        layer = QgsProject.instance().mapLayersByName("Altitude")[0]

        # Préparer le moteur d’étiquetage
        etiquette = QgsPalLayerSettings()
        etiquette.enabled = True  # activer les étiquettes
        etiquette.fieldName = "z"  # champ à afficher
        etiquette.isExpression = False

        # Style du texte
        text_format = QgsTextFormat()
        text_format.setSize(8)
        text_format.setNamedStyle("Bold")

        # Halo autour du texte
        buffer = QgsTextBufferSettings()
        buffer.setEnabled(True)
        buffer.setSize(1.2)
        text_format.setBuffer(buffer)

        etiquette.setFormat(text_format)

        # Placement simple (centres des points)
        etiquette.predefinedPosition = QgsPalLayerSettings.OverPoint

        layer_settings = QgsVectorLayerSimpleLabeling(etiquette)
        layer.setLabeling(layer_settings)
        layer.setLabelsEnabled(True)
        layer.triggerRepaint()


    def initGui(self):
        pass

    def unload(self):
        pass

    def run(self):

        if self.deja_affiche:
            layer = QgsProject.instance().mapLayersByName("Altitude")[0]
            QgsProject.instance().removeMapLayer(layer.id())
            self.iface.mapCanvas().refresh()
            self.deja_affiche = False
        else:
            self.deja_affiche = True
            self.creer_vue_altitude()

